version: "3.9"
   
services:

  redis:
    image: redis
    restart: always

        
  api:
    restart: always
    build: .
    volumes:
     - .:/code/  
    command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"

    
  celery:
    build:
      context: .
    command: 'celery -A core worker -l info'
    restart: always
    volumes:
     - .:/code/  
