# Generated by Django 4.2 on 2023-04-15 19:07
import random

from django.db import migrations, models


def make_data(apps, schema_editor):
    Tag = apps.get_model('books_api', 'Tag')
    Book = apps.get_model('books_api', 'Book')
    Volume = apps.get_model('books_api', 'Volume')
    Chapter = apps.get_model('books_api', 'Chapter')

    # создаем теги
    tags = Tag.objects.bulk_create([Tag(name=f'Tag {i}') for i in range(1,10)])

    # создаем книги
    for i in range(1, 40):
        book = Book(rus_name = f'Книга {i}')
        book.save()
        book.tag.add(*random.choices(tags, k=random.randint(1,3)))        
        
        # создаем тома книги
        for j in range(1, random.randint(1, 4)):
            volume = Volume(
                name = f'Том {j} Книги {book.rus_name}',
                price = random.randint(1,99),
                number = j,
                book=book            
            )
            volume.save()

            # создаем главы тома
            for j in range(1, random.randint(1, 10)):
                chapter = Chapter(
                    content = f'Контент {j} Тома {volume.number}',
                    number = j,
                    volume = volume,      
                )
                chapter.save()

class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_data),
    ]
